services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    command: npm run start:dev

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - clu-store-mongo-data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - clu-store-redis-data:/data

volumes:
  clu-store-mongo-data:
  clu-store-redis-data:
